### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by xEzitx** [bonnici/node-steam-trash-bot#6]
I feel that there should be some windows support for this project as it's one of the best!, it takes a lot to get the actually files up an running when I first start I thought, "Yeah install a few programs and it will work simples", well I was wrong and I've spent 2 weeks getting it to work on windows, Now I wont be offering my support on how I got it running because I don't have a clue other than following the issues from all the other projects that this requires - SteamKit2, Node-Gype, Ursa, Steam, C++ 2010 Express, and many more.

it takes way to long to get an amazing project to work on windows, on linux you're looking at 30-35minutes worth of time and that mostly spent setting up the files you require, but their should be more support in this than what is offered.

**Comment by bonnici** [comment]
Sorry but I'm just doing this for fun, and I only shared the code because I thought people would be interested. I think pretty much all of the setup stuff is external to the trashbot too, so if there was any official guide it would probably be part of node-gyp or node-steam.

I would love it if someone came up with a tutorial for how to get it working on Windows but it even took me a long time and I can't remember exactly what I did. If anyone wants to take it on they can give me a readme.md pull request and I'll add it in, but I can't do it right now.
